### ISSUE TITLE
where to download the Pre-Trained Models?

### ISSUE THREAD

**Issue by zhuojianc** [mindspore-ecosystem/mindsearch#2]
I found related pre-trained models in https://huggingface.co/Shitao, but cannot find RetroMAE-CN or related

**Comment by meiqingsui** [comment]
> I found related pre-trained models in https://huggingface.co/Shitao, but cannot find RetroMAE-CN or related

The pretrained models will be released at https://download.mindspore.cn/toolkits/mindsearch/ soon, please keep following the repo for updates
